CREATE TABLE IF NOT EXISTS public."2022popmovies"
(
    "Age" numeric,
    "Racial/Ethnic Identity" character(80) COLLATE pg_catalog."default",
    "Highest education attained" character(80) COLLATE pg_catalog."default",
    "Work Status" character(80) COLLATE pg_catalog."default",
    "Education Status" character(80) COLLATE pg_catalog."default",
    "Seen Top Gun Maverick (1=yes)" numeric,
    "emotional engage TGM" numeric,
    "Likable Character TGM" numeric,
    "Entertaining TGM" numeric,
    "Enjoyable Visuals TGM" numeric,
    "Memorable TGM" numeric,
    "Recommending TGM to a friend" numeric,
    "Watch TGM again" numeric,
    "Satisfication with TGM ending" numeric,
    "Satisfication with TGM overall" numeric,
    "Rating TGM story" numeric,
    "Seen Black Panther: Wakanda Forever (1=yes)" numeric,
    "emotional engaged with BPWF" numeric,
    "Likable Character BPWF" numeric,
    "Entertaining BPWF" numeric,
    "Enjoyable Visuals BPWF" numeric,
    "Memorable BPWF" numeric,
    "Recommending BPWF to a friend" numeric,
    "Watch BPWF again" numeric,
    "Satisfication with BPWF ending" numeric,
    "Satisfication with BPWF overall" numeric,
    "Rating BPWF story" numeric,
    "Seen Avatar: The Way Of Water (1=yes)" numeric,
    "emotional engaged with AWW" numeric,
    "Likable Character AWW" numeric,
    "Entertaining AWW" numeric,
    "Enjoyable Visuals AWW" numeric,
    "Memorable AWW" numeric,
    "Recommending AWW to a friend" numeric,
    "Watch AWW again" numeric,
    "Satisfication with AWW ending" numeric,
    "Satisfication with AWW overall" numeric,
    "Rating AWW story" numeric,
    "Seen  Doctor Strange in the Multiverse of Madness (1=yes)" numeric,
    "emotional engaged with DSMM" numeric,
    "Likable Character DSMM" numeric,
    "Entertaining DSMM" numeric,
    "Enjoyable Visuals DSMM" numeric,
    "Memorable DSMM" numeric,
    "Recommending DSMM to a friend" numeric,
    "Watch DSMM again" numeric,
    "Satisfication with DSMM ending" numeric,
    "Satisfication with DSMM overall" numeric,
    "Rating DSMM story" numeric,
    "Seen Jurassic World: Dominion (1=yes)" numeric,
    "emotional engaged with JWD" numeric,
    "Likable Character JWD" numeric,
    "Entertaining JWD" numeric,
    "Enjoyable Visuals JWD" numeric,
    "Memorable JWD" numeric,
    "Recommending JWD to a friend" numeric,
    "Watch JWD again" numeric,
    "Satisfication with JWD ending" numeric,
    "Satisfication with JWD overall" numeric,
    "Rating JWD story" numeric,
    "Seen Minions: The Rise of Guru (1=yes)" numeric,
    "emotional engaged with MRG" numeric,
    "Likable Character MRG" numeric,
    "Entertaining MRG" numeric,
    "Enjoyable Visuals MRG" numeric,
    "Memorable MRG" numeric,
    "Recommending MRG to a friend" numeric,
    "Watch MRG again" numeric,
    "Satisfication with MRG ending" numeric,
    "Satisfication with MRG overall" numeric,
    "Rating MRG story" numeric
);


INSERT INTO "2022popmovies" ("Age", "Racial/Ethnic Identity", "Highest education attained", "Work Status", "Education Status", 
								"Seen Top Gun Maverick (1=yes)", "emotional engage TGM", "Likable Character TGM", "Entertaining TGM", "Enjoyable Visuals TGM", "Memorable TGM", "Recommending TGM to a friend", "Watch TGM again", "Satisfication with TGM ending", "Satisfication with TGM overall", "Rating TGM story", 
								"Seen Black Panther: Wakanda Forever (1=yes)", "emotional engaged with BPWF", "Likable Character BPWF", "Entertaining BPWF", "Enjoyable Visuals BPWF", "Memorable BPWF", "Recommending BPWF to a friend", "Watch BPWF again", "Satisfication with BPWF ending", "Satisfication with BPWF overall", "Rating BPWF story", 
								"Seen Avatar: The Way Of Water (1=yes)", "emotional engaged with AWW", "Likable Character AWW", "Entertaining AWW", "Enjoyable Visuals AWW", "Memorable AWW", "Recommending AWW to a friend", "Watch AWW again", "Satisfication with AWW ending", "Satisfication with AWW overall", "Rating AWW story",
							   "Seen  Doctor Strange in the Multiverse of Madness (1=yes)", "emotional engaged with DSMM", "Likable Character DSMM", "Entertaining DSMM", "Enjoyable Visuals DSMM", "Memorable DSMM", "Recommending DSMM to a friend", "Watch DSMM again", "Satisfication with DSMM ending", "Satisfication with DSMM overall", "Rating DSMM story",
								"Seen Jurassic World: Dominion (1=yes)", "emotional engaged with JWD", "Likable Character JWD", "Entertaining JWD", "Enjoyable Visuals JWD", "Memorable JWD", "Recommending JWD to a friend", "Watch JWD again", "Satisfication with JWD ending", "Satisfication with JWD overall", "Rating JWD story",
								"Seen Minions: The Rise of Guru (1=yes)", "emotional engaged with MRG", "Likable Character MRG", "Entertaining MRG", "Enjoyable Visuals MRG", "Memorable MRG", "Recommending MRG to a friend", "Watch MRG again", "Satisfication with MRG ending", "Satisfication with MRG overall", "Rating MRG story")
VALUES (18, 'Asian', 'High school degree', 'Part-time', 'Not a Student', 1, 5, 4, 5, 4, 4, 5, 5, 5, 5, 4, 1, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL), 
       (22, 'Latino', 'Bachelors degree', 'Full-time', 'Not a Student', 1, 4, 3, 4, 4, 4, 4, 4, 4, 3, 3, 1, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL), 
       (23, 'Black', 'Some college/ Associates degree', 'Part-time', 'Part-time student', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 5, 5, 5, 4, 5, 4, 4, 5, 5, 4,  0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 5, 5, 4, 5, 3, 5, 4, 5, 5, 5), 
       (23, 'Latino', 'Bachelors degree', 'Full-time', 'Not a Student', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,	1, 5, 4, 4, 3, 3, 2, 2, 3, 4, 3, 1, 4, 5, 3, 5, 4, 5, 4, 5, 5, 4), 
       (22, 'Black', 'Some college/ Associates degree', 'Unemployed', 'Full-time student', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 4, 5, 5, 4, 4, 5, 4, 5, 5, 4, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 3, 5, 4, 4, 4, 3, 4, 4, 3, 4, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 4, 5, 4, 3, 3, 3, 3, 3, 4, 4);


